variable "project_name" {}
variable "env" {}
variable "alb_name" {}
variable "internal" {}
variable "vpc_id" {}
variable "sg_cidr_blocks" {}
variable "subnets" {}
variable "acm_arn" {}
variable "target_group_arn" {}
variable "zone_id" {}
variable "dns_name" {}