format_version: 10
pipelines:
  TerraformDestroy:
    group: defaultGroup
    label_template: "${COUNT}"
    lock_behavior: none
    display_order: -1
    materials:
      ansible:
        git: https://github.com/raki009/terraform-practice
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: terraform
                    arguments: ["init", "-backend-config=env-dev/state.tfvars"]

                - exec:
                    command: terraform
                    arguments: ["destroy", "-var-file=env-dev/main.tfvars", "-auto-approve"]